apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app
  namespace: fastapi-app
  labels:
    app: fastapi-app
    release: monitoring
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi-app
  template:
    metadata:
      labels:
        app: fastapi-app
        release: monitoring
    spec:
      containers:
        - name: fastapi-app
          image: protocs2/fastapi-app:latest
          ports:
            - containerPort: 8000
